# fly.toml app configuration file generated for lapis20231014 on 2023-10-14T13:18:04+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lapis20231014"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
